language: c

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda env update -n base -f environment.yml

script:
  - jlpm
  - jlpm build
  - jupyter labextension link .
  - pip install -e .
  - jupyter serverextension enable --py jupyter_archive
  - pytest jupyter_archive/
